### ISSUE TITLE
JmsSessionFailedTest hangs intermittently

### ISSUE THREAD

**Issue by kevinearls** [fusesource/hawtjms#1]
This test sometimes hangs during teardown, as shown in the portion of the stack trace shown below.  This is similar to problems we've seen with the QPID client in the past.

"main" prio=10 tid=0x00007f757c008800 nid=0x746a waiting on condition [0x00007f7583a94000]
   java.lang.Thread.State: WAITING (parking)
    at sun.misc.Unsafe.park(Native Method)
    - parking to wait for  <0x00000000f0ab59a0> (a java.util.concurrent.CountDownLatch$Sync)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:994)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:236)
    at org.fusesource.amqpjms.provider.ProviderRequest.getResponse(ProviderRequest.java:97)
    at org.fusesource.amqpjms.provider.DefaultBlockingProvider.destroy(DefaultBlockingProvider.java:79)
    at org.fusesource.amqpjms.jms.JmsConnection.close(JmsConnection.java:162)
    - locked <0x00000000f0b511b8> (a org.fusesource.amqpjms.jms.JmsConnection)
    at org.fusesource.amqpjms.jms.JmsSessionClosedTest.tearDown(JmsSessionClosedTest.java:47)
    at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

"VM Thread" prio=10 tid=0x00007f757c0eb000 nid=0x746d runnable 

"GC task thread#0 (ParallelGC)" prio=10 tid=0x00007f757c01e800 nid=0x746b runnable 

"GC task thread#1 (ParallelGC)" prio=10 tid=0x00007f757c020800 nid=0x746c runnable 

"VM Periodic Task Thread" prio=10 tid=0x00007f757c122800 nid=0x7474 waiting on condition 

JNI global references: 274

**Comment by kevinearls** [comment]
I think this occurred because I ran it on a CI box, so it was running against an activemq snapshot that was built with Proton 0.6 instead of our version.

I'll back out the ignore.
